from . import patient
from . import appointment
from . import treatment
from . import dental
from . import insurance
from . import service
from . import hr_employee
from . import res_partner
from . import account_move